// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnPgLABNLYypa8UlLzmcmMHkldbd9WDwI',
    appId: '1:27155348743:web:15b62c35cb03332ac1d9a2',
    messagingSenderId: '27155348743',
    projectId: 'passtime-95bad',
    authDomain: 'passtime-95bad.firebaseapp.com',
    storageBucket: 'passtime-95bad.firebasestorage.app',
    measurementId: 'G-9VPZB5C4VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgjqd22m_YCNrZXxh_rFd159YkpWKUsxU',
    appId: '1:27155348743:android:e5d473ebfe8afda3c1d9a2',
    messagingSenderId: '27155348743',
    projectId: 'passtime-95bad',
    storageBucket: 'passtime-95bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgmhKral8eHdkZaaTiUzLC95HQ_l4oW0U',
    appId: '1:27155348743:ios:13f9609c6498c800c1d9a2',
    messagingSenderId: '27155348743',
    projectId: 'passtime-95bad',
    storageBucket: 'passtime-95bad.firebasestorage.app',
    iosBundleId: 'com.example.passtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgmhKral8eHdkZaaTiUzLC95HQ_l4oW0U',
    appId: '1:27155348743:ios:13f9609c6498c800c1d9a2',
    messagingSenderId: '27155348743',
    projectId: 'passtime-95bad',
    storageBucket: 'passtime-95bad.firebasestorage.app',
    iosBundleId: 'com.example.passtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnPgLABNLYypa8UlLzmcmMHkldbd9WDwI',
    appId: '1:27155348743:web:157e73c65f4a3194c1d9a2',
    messagingSenderId: '27155348743',
    projectId: 'passtime-95bad',
    authDomain: 'passtime-95bad.firebaseapp.com',
    storageBucket: 'passtime-95bad.firebasestorage.app',
    measurementId: 'G-HS11DS78MR',
  );
}
